export const eslintConfigUniIgnores = [
  '.cache',
  '.idea',
  '.vscode/*',
  'typings/',
  'CHANGELOG.md',
  //
  '_cache/',
  'cache/',
  //
  '.build/',
  '_build/',
  'build/',
  'build-test/',
  'build-local/',
  //
  '.dist/',
  '_dist/',
  'dist/',
  //
  '.deploy/',
  '_deploy/',
  'deploy/',
  //
  'node_modules',
  '_documents/',
  'public/',
  'static/',
  //
  'src/styles/vars/_output',
  'src/libs/polyfills',
  'src/libs/node_modules_aliase',
  'src/assets',
  'src/assets/react-icons-ext',
  'src/libs/**/*',
];
