export const DEBUG_CONST_KEYS = {
  __DEBUG_UQ_VCONSOLE__: '__DEBUG_UQ_VCONSOLE__',
  __DEBUG_UQ_DEBUGBAR__: '__DEBUG_UQ_DEBUGBAR__',
  //
  __DEBUG_UQ_FORCE_PROD_API__: '__DEBUG_UQ_FORCE_PROD_API__',
  __DEBUG_UQ_FORCE_CDN_API__: '__DEBUG_UQ_FORCE_CDN_API__',
};
