/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms.index'
import { Route as Product2IndexRouteImport } from './routes/product-2.index'
import { Route as Product1IndexRouteImport } from './routes/product-1.index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy.index'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as PartnershipIndexRouteImport } from './routes/partnership.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as EncyclopediaIndexRouteImport } from './routes/encyclopedia.index'
import { Route as CooperationIndexRouteImport } from './routes/cooperation.index'
import { Route as CookiesIndexRouteImport } from './routes/cookies.index'
import { Route as ContactIndexRouteImport } from './routes/contact.index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog.index'
import { Route as AboutStoryRouteImport } from './routes/about.story'
import { Route as AboutPartnersRouteImport } from './routes/about.partners'
import { Route as AboutHonorRouteImport } from './routes/about.honor'
import { Route as AboutCompanyRouteImport } from './routes/about.company'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const Product2IndexRoute = Product2IndexRouteImport.update({
  id: '/product-2/',
  path: '/product-2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Product1IndexRoute = Product1IndexRouteImport.update({
  id: '/product-1/',
  path: '/product-1/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipIndexRoute = PartnershipIndexRouteImport.update({
  id: '/partnership/',
  path: '/partnership/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaIndexRoute = EncyclopediaIndexRouteImport.update({
  id: '/encyclopedia/',
  path: '/encyclopedia/',
  getParentRoute: () => rootRouteImport,
} as any)
const CooperationIndexRoute = CooperationIndexRouteImport.update({
  id: '/cooperation/',
  path: '/cooperation/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesIndexRoute = CookiesIndexRouteImport.update({
  id: '/cookies/',
  path: '/cookies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutStoryRoute = AboutStoryRouteImport.update({
  id: '/about/story',
  path: '/about/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPartnersRoute = AboutPartnersRouteImport.update({
  id: '/about/partners',
  path: '/about/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHonorRoute = AboutHonorRouteImport.update({
  id: '/about/honor',
  path: '/about/honor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCompanyRoute = AboutCompanyRouteImport.update({
  id: '/about/company',
  path: '/about/company',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/honor': typeof AboutHonorRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/story': typeof AboutStoryRoute
  '/changelog': typeof ChangelogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cookies': typeof CookiesIndexRoute
  '/cooperation': typeof CooperationIndexRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/partnership': typeof PartnershipIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/product-1': typeof Product1IndexRoute
  '/product-2': typeof Product2IndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/honor': typeof AboutHonorRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/story': typeof AboutStoryRoute
  '/changelog': typeof ChangelogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cookies': typeof CookiesIndexRoute
  '/cooperation': typeof CooperationIndexRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/partnership': typeof PartnershipIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/product-1': typeof Product1IndexRoute
  '/product-2': typeof Product2IndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/company': typeof AboutCompanyRoute
  '/about/honor': typeof AboutHonorRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/story': typeof AboutStoryRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cookies/': typeof CookiesIndexRoute
  '/cooperation/': typeof CooperationIndexRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/partnership/': typeof PartnershipIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/product-1/': typeof Product1IndexRoute
  '/product-2/': typeof Product2IndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/company'
    | '/about/honor'
    | '/about/partners'
    | '/about/story'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/cooperation'
    | '/encyclopedia'
    | '/features'
    | '/integrations'
    | '/partnership'
    | '/pricing'
    | '/privacy'
    | '/product-1'
    | '/product-2'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/company'
    | '/about/honor'
    | '/about/partners'
    | '/about/story'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/cooperation'
    | '/encyclopedia'
    | '/features'
    | '/integrations'
    | '/partnership'
    | '/pricing'
    | '/privacy'
    | '/product-1'
    | '/product-2'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about/company'
    | '/about/honor'
    | '/about/partners'
    | '/about/story'
    | '/changelog/'
    | '/contact/'
    | '/cookies/'
    | '/cooperation/'
    | '/encyclopedia/'
    | '/features/'
    | '/integrations/'
    | '/partnership/'
    | '/pricing/'
    | '/privacy/'
    | '/product-1/'
    | '/product-2/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutCompanyRoute: typeof AboutCompanyRoute
  AboutHonorRoute: typeof AboutHonorRoute
  AboutPartnersRoute: typeof AboutPartnersRoute
  AboutStoryRoute: typeof AboutStoryRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  CookiesIndexRoute: typeof CookiesIndexRoute
  CooperationIndexRoute: typeof CooperationIndexRoute
  EncyclopediaIndexRoute: typeof EncyclopediaIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  PartnershipIndexRoute: typeof PartnershipIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  Product1IndexRoute: typeof Product1IndexRoute
  Product2IndexRoute: typeof Product2IndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-2/': {
      id: '/product-2/'
      path: '/product-2'
      fullPath: '/product-2'
      preLoaderRoute: typeof Product2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-1/': {
      id: '/product-1/'
      path: '/product-1'
      fullPath: '/product-1'
      preLoaderRoute: typeof Product1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership/': {
      id: '/partnership/'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia/': {
      id: '/encyclopedia/'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooperation/': {
      id: '/cooperation/'
      path: '/cooperation'
      fullPath: '/cooperation'
      preLoaderRoute: typeof CooperationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies/': {
      id: '/cookies/'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/story': {
      id: '/about/story'
      path: '/about/story'
      fullPath: '/about/story'
      preLoaderRoute: typeof AboutStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/partners': {
      id: '/about/partners'
      path: '/about/partners'
      fullPath: '/about/partners'
      preLoaderRoute: typeof AboutPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/honor': {
      id: '/about/honor'
      path: '/about/honor'
      fullPath: '/about/honor'
      preLoaderRoute: typeof AboutHonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/company': {
      id: '/about/company'
      path: '/about/company'
      fullPath: '/about/company'
      preLoaderRoute: typeof AboutCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutCompanyRoute: AboutCompanyRoute,
  AboutHonorRoute: AboutHonorRoute,
  AboutPartnersRoute: AboutPartnersRoute,
  AboutStoryRoute: AboutStoryRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  CookiesIndexRoute: CookiesIndexRoute,
  CooperationIndexRoute: CooperationIndexRoute,
  EncyclopediaIndexRoute: EncyclopediaIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  PartnershipIndexRoute: PartnershipIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  Product1IndexRoute: Product1IndexRoute,
  Product2IndexRoute: Product2IndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
